services:
  api:
    build:
      context: .
      dockerfile: ./code/deployment/api/Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./code/deployment/api:/app
      - ./models:/app/models
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: ./code/deployment/app/Dockerfile
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./code/deployment/app:/app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge